build:
	gb build

run: build
	./bin/cloudflare-dyndns \
		-key "" \
		-email "cole.mickens@gmail.com" \
		-records "*.mickens.xxx,mickens.xxx,*.mickens.io,mickens.io,recessionomics.us,www.recessionomics.us,*.mickens.me,mickens.me,*.mickens.tv,mickens.tv,*.mickens.us,mickens.us,cole.mickens.us"
